#apiVersion: 1

---
kind: Service
apiVersion: v1
metadata:
  name:  nginx-svc
spec:
  selector:
    app:  nginx
  type:  LoadBalancer  # 일반적인 경우에는 LoadBalancer
  ports:
  - name:  nginx
    port:  80
    targetPort:  8080

---

apiVersion: v1  # dokcer tag (version 정보)
kind: Pod       # k8 object - Pod, Service, ReplicaSet, ReplicaControll, Deployment
metadata:       # kind Pod의 identifier 정의
  name: nginx
  labels:
    name: nginx
spec:           # kind Pod의 포함되는 container 정보
  containers:
  - name: nginx
    image: hifrodo/nginx:v1
    ports:
      - containerPort: 80
